### ISSUE TITLE
[Sybil Report]

### ISSUE THREAD

**Issue by ca6acas** [LayerZero-Labs/sybil-report#1429]
# Reported Addresses
0xfbd0aae0ae149879d6c686460b54977836ef03d9
0xfed53f593c18f261a3a35a423bf74837dd6c722f
0xfee88c73750ce6a5c8a1e9576bced64ef8a85c73
0xffad4836b73a1ce5d86230e98cb3e52cde35379e
0xf93814de7f4d716fabc43b483c67114e990b8284
0xf850e36dfd611c12abc05b7678fed3ec6a9e5474
0xf7eedd2bc737406d46d4cbfd51c2e90a6979987d
0xf7be69a2faad5dab83724bbf77daaecec0dd36f9
0xf4ccf70c77b6507d149a79df883c367f0d8b10fa
0xe972b09e8f2448a79f12ab2c984eb6117985a9da
0xe8ae74ba07e324461c8dfb76aa5267be2a9a9be9
0xe755b6f4bc4e880ba313718e71eeddc3a027ac92
0xe45d5f9462ab7a5f34a1feed071ff8b390cebb62
0xe256f341e5ff53143edeee96ed8a05669e849cdb
0xe06b33aacf760e52a8b837f7addef7519a8b8371
0xdfba6f87a8ab216b87ab1e73fa0c9ca0e7f1d72c
0xdb6c49e63896903803b7443a32fab10779e7b6dc
0xd819b6346ae0afd3739c77685597e79e6d23d943
0xd72c4196f98af2dc99d588560d48381f067eb19c
0xd379a609c1d0ce91c911fa804493ea39b7432e4a
0xd30ceb1a0cdd3b71b3af4b337c3e259f954c0443
0xd204e706cef815bf64be52dbcf8472b8029a3219
0xd141224bd2c0f4f0bd709b6ec8f63052bb90b3c4
0xcf4d9e51091d006c6038c2b96bd03c65bccc2ad5
0xcded98a3f60a7ba1579dc9fe41a603ce6096d846
0xcac6c4a5a8c4bd182be589f24bbcfb850527010e
0xc30a382cb4188ce7741267fbf7c0c35f50bc6b16
0xc2703ea9da719578d5627f2d7e5b471e9281a268
0xb68e09447b7d6ce3bb458eff585aa196a8154346
0xb55443ed4394cf76fd394fb93dfbd90ab143ca30
0xb244bff215b25fc045b51d777d4ed339c11acff1
0xb0dc3b1f04529984dc65a0a541797b184feb50b9
0xa8a3ecddb6e37fc7f390e3f7d9ab91617e4b8013
0xa5274f93c793c5d315f857212c7f407b0e6317aa
0xa3f539a018ac665243ef188cc12c027c542a91a4
0xa37ee1f0294aec1577f4349927208f7e6aa0063c
0x9d15128cef555c378a6ff467b046a35f9fc2ee18
0x9b5c85e3f6c4432fb45131670b3a9e1137e19ad7
0x998a19961d0c8c27ee516c2c89e3db4cc75c6230
0x96d8c22af4b363fd70d5dba37eeae04af70f05de
0x9443ff2831cd4d01d6b059017019cc04869e4887
0x96462e9f28d18fd5350a3c9eb447589a53ab5607
0x90e532f1be819e568efa975f29e1b4bc8d746cf8
0x9009c97b7bb4c0faff1aea75338f93c33b1dfacd
0x8ec179f4202e4216358f91ef53aee2d7e6fd825e
0x8cb63ef92c592cf254190d9a36c8878b7a18c6fb
0x8bdb8923dee1ea30cd54978fc25031d31a33cd98
0x826b60531dfb394a3af611168aa3c20dfc4c0dad
0x7ca36c47dded093515ba3fff7cc296b59d2012b4
0x7a5ee74414213611378dbbcc40f64b58c3d2a46b
0x79dbebb1fb7bee5447800f1eee59a9f193e227f3
0x78ade0fc66c6c06886f5f3e6e64cb7a5f37c2523
0x71d5fc6d64b49f02f779aa5ec1eaf86ecc685da5
0x72bed5866057e80f0e4c1b379ab677b4cfe23d90
0x74485b4837f740aa694ca9c0239132429258cd20
0x747d1f5d6ebf3bad8d3a88264b04189d044f2124
0x74b30c7078789e299d7e6478bd77086dba02198f
0x6c31212a23040998e1d1c157ace3982abdbe3154
0x6737ada10678ccd0e52219e39d031dd3960d16a2
0x5d5030efc14b0ca0f86fbef7cb8b3efdadda6e99
0x646ee99bbe1b3edc3090e80081d0040d8982be11
0x537542d43722Aa54803aD4C70e2438b2867001Cd
0x593675ae888e205bbc3c3548ecf21b962878bb0d
0x58a4f8fdc5d6b027bd8fc3e4726b2d0f19d728b5
0x57b95fff447f8a8a36e480ef1316ca49b7879464
0x50d70dfe9a663937e7c1e2030f73e922e2b7fb60
0x4fed4414b64e8b7e201c5659f1c4cc6e4b28c604
0x4dd4b5d6f696c5367444c0cce7680daae8984a34
0x4d1dee697dc96534c0c3c5e2da242f43177bb0b6
0x4c6e9aa545834f4c2989112d7c0269aa6d08d7f6
0x42b35351897f35aeb6c5b2d9eefe84191c6d724a
0x428a0fe9a63ccf5d2ceac4603965da287d7a1b74
0x3f8fedfe8bd241ca27b239cac170c8d456008101
0x3a6ddd419bf3632b1625ca3e7e6f5e47f3794db1
0x39168890cf996d236527f7636a5fab410dc5af46
0x363868e87c7653ea7afbd9e02a0b4dce57191206
0x2fdff4169bd11317cdc895573066dd71e87ca67c
0x2eb760187b952a2023614308af7617ec1ed1eec0
0x2e443da88e1334aeb320208a604a0ad7ec1f9c3a
0x2af7af50eb37eb9f8a5e2476dab0b6ab036de45c
0x2bb9b93baf8fb9562441d511397acf8defffa012
0x2c8f38745ee758da565ab9369350744c50371cbc
0x2d9b6162479646b9b704b9a1e21c90662175be3d
0x239f91a8f63ce8b446cd495c182b5ffe9ccfa623
0x23f7013a09214fd6f73746d226d4ccfd015ff0e4
0x2a66ea719503403df6d94617701f165d9b3e321d
0x2ae074650908396cea81720ec859df5834a77b31
0x1cc4aa6689a2930def7d88703e3d777f6065aa69
0x1d62797ef1f4513917a55a7ca4e340f9f6e3897d
0x2098e99b3ce27c5a8fa099a6a860fe3760cab6b5
0x20ad8749fc85d1a51756e037a0cfd9b814da0f94
0x137a8cff9cf9a0b33d894430efa707544e86363b
0x17424ccccae665fa85c3d424540e9fa87a5af3a5
0x1949c0f91325d0667c2e7cf8d47bcafa9c3014f2
0x1a84ee8258331aa7f63f85223ca0b40159a5a49f
0x0db48ff731361f27d742faff27f0e89f027a3c66
0x0e78e8a211da168784f65fd9c7067b679f05f1ad
0x0ec731f35ebc105ef247f366bd606d666640e3aa
0x0f4542be410f10decd914e533674d38221289881
0x0A9d59E0A517fE4CeE076EfC1DD456D4eec24A75
0x06a13e78f88f60e951df918a1a285fe14e0ce7c3
0x06f3b9bcb455ce1d13bf689f3af3d4b7d856c9a8
0x06fded36509dfd28ecec6c91560ce915ab868242
0x090367d14927c468ea149701b46b10c6b764aa79

# Description
Hello, in a chat in a telegram group about airdrops, I saw a man who was talking about his big farm of accounts, he said that he had over 100 LayerZero wallets and each one had a private proxy and VPN. I read his entire post history and saw that about 4 months ago he was bragging about his huge farm of 500 wallets on which he was doing MEME airdrop tasks. In the task to get airdrop, it was needed to have at least 69 MEME on the wallet and this person threw a screenshot of how he sent 69 MEME to all his 500 accounts through a special service where you can send tokens to a large number of wallets at once. That's where I caught him. On the screenshot he did not censor the address bar. I manually typed in that address and went to the transaction page and got a list of all his 500 wallet addresses. I manually checked all 500 accounts and found the 100+ accounts he was talking about. I'll attach a link to the transaction and you can see for yourself.
https://etherscan.io/tx/0xa5512119f969b6595aaadb666f566a40df423a90aac99d82227e16be6f66f45d
 So 500 newly created wallets that he sent tokens to from one account. And these accounts were not used in any other way. except 100 of his main accounts where he performs activities to get drops from big projects like Layerzero etc.
# Detailed Methodology & Walkthrough
I just found a farmer who burned himself and gave a screenshot of his wallet addresses with proof of ownership and I tracked all the wallets he owns and filtered out those addresses on which he worked LayerZero
# Reward Address (If Eligible)
0x4330e88921ae619aF6c9eCf13e42A76F48951016

**Comment by itzabhi69** [comment]
Hi, the things he mentioned that he saw someone in a group chatting about airdrops the whole story is truly false and there is nothing such like that in any of the wallets mentioned. The activity, the wallet age, funding address and all doesn't even match up. 

This was an airdrop held by a famous airdrop twitter page known as Crypto Telugu - @CryptoTeluguO

Here is the giveaway distribution link - https://x.com/CryptoTeluguO/status/1747991248152019151

Tx hash - 0xa5512119f969b6595aaadb666f566a40df423a90aac99d82227e16be6f66f45d

The tx hash is mentioned in the giveaway tweet and none of the wallets mentioned above are sybils. 
This report is pointless. Thanks!
