### ISSUE TITLE
[Merkly and samll txns clusters]

### ISSUE THREAD

**Issue by haryana993** [LayerZero-Labs/sybil-report#2928]
# Reported Addresses
0x8638d22d2da708269cccae09e09bded1ff5e2e42
0x8c9e45583f685e1b2bfef9920406ab8c37e3668f
0xb23efd0ff84ef9e66e15fed03be5a6bc308a8db5
0x03762f607b3dcbb7e5b4b59c460bfc480fa91263
0x9fc6865e2c1f23672849842708a223c4eacaa950
0xbfe5f767b97da6f4bf4030d085de903d68345142
0x8d3debe408858a8abe2ea977bdc18ec8201c05d7
0x1b0651606b2acf5e1308f510c75a8106dcf1a266
0xc8a8bf2e37fc1a205fb8281a6a866bc8f7110041
0xafe900f6771cb5522d8c41cf51c0a0d637b71d5e
0x90b4f7457d73eb8795edff791061666d2a3df398
0xd4e9b6a6e74e58b50561375795306030d02f1959
0x6baa1c182e6525ccc0958ce3ed9847682e11dbf5
0x9534e4beb4f7e07bb88f4c6a067d666c29e1b433
0x7dc6272db0523ce8d0270920e94f7c37d3bbea1b
0x4c1b1d3636eac32f528bb5103a345f8633cad9ff
0x2cf3bc994c63df03e3438226cc2e52ffa980aee7
0xbd33a203f18335a143a06f2800e1db45df8b01d2
0x5122c3b4de32d93efae914382c08d02fb8348353
0xfa15f74278466dcfba6a8efd2aa8e1b235bccce4

# Description
These addresses are not connected each other or not owned by single user but they are involved in sybil activites like more than 50% of txns are only on merkly and/or 30% + small txns means txn value less than 0.01$ 

Here is the detailed disciption of addresses in excel sheet
[LayerZero_Sybil.xlsx](https://github.com/LayerZero-Labs/sybil-report/files/15359660/LayerZero_Sybil.xlsx)

# Detailed Methodology & Walkthrough

Actually i used dune tools 

https://dune.com/satoshi_choobs/merklyl0check
https://dune.com/zhoushao/layerzero-sybil-checker

You can cross check them also
# Reward Address (If Eligible)
0x5c19083C9Aea8b6C16eb0a25d03A01Cc3384dD58

**Comment by Danilpepsi** [comment]
People like this one try to ruin the accounts of honest people!
+ want to make money on this!
Yes, I didn’t do Merkly, but only out of motivation to develop and develop with this project!!!
