### ISSUE TITLE
[Sybil Report]

### ISSUE THREAD

**Issue by sakotn** [LayerZero-Labs/sybil-report#5045]
# Reported Addresses

0x9d5b4610AFB7d6853196C7f1EEdE36190AD89aD3
0x0C5cb7DA77753A1A8F8Fb1236E82FA3b74338b4f
0x32D9D6191b53dfbb96964B1491261bE74Ae6D3Bf
0xc4857E98713d874a11c186F17485a848B1abFA2E
0xb1c5FccdED9B93c2390E047228F2FA7c92e45B0C
0x0a8404f88bb71cb93B3B9108eBA4b2a3A42bbD7e
0x56cD74e8f5F373dccCf736929dA25b0140Ae9765
0x45fd9dfb407d239b784a9b862f9551baB09A8F26
0x47b83c738fE10D3A8A63882C220Ad085537c79D9
0xb3927b5aeFDBaa3A8Ca4EeB0D5962B81DFa9826d
0x3c109598296EbeC7B03c9CfB9B8a2ebA2738dD7a
0x833403A8de7AfD78F35Cf7DF4b0eCf37DFfF5C7F
0x0E85376C2b5c5990f724626C0061f77678C5dA4a
0xC5d1f3E5d23D92569A6C202A952A385f5D491F31
0xaC682ee02f9776bC7a3bb1278Eb170adc2392CE0
0xf468C4BB84633ed93C092D8d5338ed1AAA30F4AF
0xda5084FECCc83B49AEF7d76e50f1f94E01872b94
0x1D9a85Adbe46aF22c0Ee9E78af2B93121464c221
0x69f00D231f4E69Ccb926649d0BAbf183ad2542D4
0xc058c160b687E8873920Beaa26c6424377008726
0x8b7aE4849Be8E79Af3898FF512daa8e8bA7dca06
0x2a9e17628398Cd890c38692E5089C25Ce3987cC8
0x8c946fAeEB47bec513695012C2351ce74489863E
0xe56Ef5816B69a1baB425Fdb8Fb7934Ba3DDfBCC2
0x79021Ee4E5f9239c670182B2c8d332daF27d5C2e
0xce1a783560516fe66ab20009DD35D5173C7F37e3
0xE9C77E3c4f830eE1C9F2B10D79ce13989EdB3B55
0x7Bca44BB3D880959b906D2ab1c8aEab9b7bDb33B
0x28943Bb8b4Ad3522d337FBafD98effcc44a6A4f2
0x3B912DA89FE348CaCd5E307042C31496952fa0d4
0x37B55A26abA070789A31A23fd6c154AF3875ecf4
0x691c054F50cb5529AaF20B71C0e31C09430bf115
0xE75fA14f6A240b9cb44Ff430674Db5303e480672
0x76806E402731C322e0fE4E4b22c1b808f741067a
0x5faD31a0635e8fEfFAD197ffd814BC8A7867DD8E
0xB96269e6190aED48e25A81D2349E93af225E8154
0x838439d7347169E4737f3A6aD78ed83208f7c692
0x19E44E4D4B1e94EE4fD51E26068aF4455CFE65b8

# Description

multisender from 0xd276a87e3422f470064689e223d1a07a5fe27f7a 
2022-10-22 at intervals of a couple blocks

# Detailed Methodology & Walkthrough

![CleanShot 2024-05-18 at 12 03 40@2x](https://github.com/LayerZero-Labs/sybil-report/assets/105765683/b475f35e-f35a-4095-a145-28c22d7917d8)
![CleanShot 2024-05-18 at 12 04 10@2x](https://github.com/LayerZero-Labs/sybil-report/assets/105765683/263c1cb5-facc-419f-ac59-7c1df322f894)

# Reward Address (If Eligible)

0x4c082F0947ef1bb0Bb2384F3222051AD1c131Eab

**Comment by bencoop757** [comment]
Please delete your report, you are mistaken, because of your lies I will suffer a lot. and 20 more innocent people, look at their addresses
Two years ago I held a lottery and sent a prize to the winners. This was before L0.
I live in Kharkov, Ukraine, I have a war right on my doorstep, and you too with such meanness.
Remember about karma, all evil always returns 100 times

**Comment by sakotn** [comment]
10% на зсу закинешь

**Comment by bencoop757** [comment]
Я постоянно доначу , с этого дропа обязательно.

**Comment by sakotn** [comment]
удаляй
