### ISSUE TITLE
[Sybil Report-cluster of 25 wallets out of which 1 wallet already found as sybil in phase 1-reporting pending 24 wallets]

### ISSUE THREAD

**Issue by anishk5544** [LayerZero-Labs/sybil-report#5676]
# Reported Addresses
0xd70A9dcD0753dD7aD9Cc49d434B91659A6165512 
0x130aA828E57dcaAf7acD531d1Dd7d3Af6E382Bb8 
0x35AAC97Ef243579495117B16D16aE98fD54A602D
0x13E6e2e382a0C5Dc822A5f73D77F67d2B4150760 
0x703F384b2236dBA263383AEA44859D70ec008a99
0x3f1b5c3D0d6290Ff49133BF6343873d50b2e1e0e 
0x5C7285BAF636B40A4B1F91FDC647C8f13A357533
0x6E0b750Efa5fB1BFEd2a31aC6Bb741551Bcc98f4 
0x8506f2A118221a74888AAc2912dd7664067E70eA
0xB48470B3122ac663cb428156Fb9f3f27347cA93E
0x883dE328a01cefCFc8E22D0b692fF6EC344EF665
0xf1f12A06Ca57BFb6f8d2b075577a6d138f1d70e8
0xcC48991dca9cEF5fd9E1A50c2F07942d1C78D973
0xCf34403eCbA0299b8F6B86d34a3A008faB5A06cD
0x6cFF024fEb094e2bd577038ccb7ba5DF8b1E043C 
0xf0B6B702D0a757c1319066c60C318Db0B84E50d9
0x8352EF12744dbD5F87286e8171e4366E6198BaEC
0xC442e7EcA93A6b0f51Ded53359e60418851e440B 
0x4f9386c78bdd2Fdbfc64b02348Eaa406390e3809 
0x0E38468F4A600d3c5a23633C5B2c5F2Be64A9b1a
0x5E020023d2A4ee87d0A857463dEd02DD73991803 
0x566c10921F6d286EDb15371EDa3EA3a59ca06d76
0x35e66f648E34617966296CACD6eb3114b74b8b9e
0xD0B74BAE747a7756644B1f453577449055693A6c 

# Description its a cluster of 25 wallets out of which 1 wallet already found as sybil in phase 1 so reporting 24 wallets. all wallets interconnected between each other with exchange deposit address-attached detailed report pdf. Also wallets are linked with in and out transactions between each other-details in the attached pdf. checked the layerzero transaction in the layerzeroscan and most of the wallets have similiar pattern transactions so all wallets belong to same person.

# Detailed Methodology & Walkthrough Used arkham to track the deposit address of all wallets and manually verified the linked exchange deposit address. checked manually each wallet in and out transactions with arkham and confirmed the transaction links between each wallet. Used Layerzero scan to track the layerzero transactions of each wallet manually and found out the similiar pattern in transactions. please check attached detailed report

# Reward Address (If Eligible) 0x1F8F40AeAeC6850A20952EDCAfaB8801F37Bf631

[degenwhale.xlsx](https://github.com/LayerZero-Labs/sybil-report/files/15362758/degenwhale.xlsx)
[degenwhale 25 wallet detailed report.pdf](https://github.com/LayerZero-Labs/sybil-report/files/15362759/degenwhale.25.wallet.detailed.report.pdf)
![wallet 10 58 11 12 1 connected binance](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/5f8cfa6b-9d92-4d14-9af8-812ae93ec877)
![wallet 1 6789 connected binance address](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/65076dbe-c0d5-4d70-b275-c2d4cbb701e4)
![wallet 1 4 5 connected binance address](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/98b45a86-0197-47c2-84f7-3636b938fb9e)
![wallet 1 2 3 linked binance deposit address](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/a676e435-9a33-447c-9244-0603d00afed3)
![wallet 6 linked binance address accounts](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/8d81b416-dea2-48ea-9e33-f067db38c24b)
![wallet 5 linked binance address linked wallets](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/0c1c5f4f-ac1a-4f58-b9fc-0f3d0a956cb3)
![wallet 4 links](https://github.com/LayerZero-Labs/sybil-report/assets/140479641/3cfad368-97a0-47fe-89e0-3cb122a35830)

**Comment by anishk5544** [comment]
[degenwhale.xlsx](https://github.com/LayerZero-Labs/sybil-report/files/15362764/degenwhale.xlsx)
[degenwhale 25 wallet detailed report.pdf](https://github.com/LayerZero-Labs/sybil-report/files/15362765/degenwhale.25.wallet.detailed.report.pdf)

**Comment by SriCrypt** [comment]
you did multiple accounts : https://debank.com/profile/0x8a7c6b171dd5c2ac08162b7970fc2aa73035c963     remove it. other wise pay the price

**Comment by CryptoCat101** [comment]
@LayerZero-GH My wallet 0xB48470B3122ac663cb428156Fb9f3f27347cA93E is included in this list by @anishk5544. I dun no how he marked me as a sybil. My wallet is 1300 + days old and having over 600$ fees on L0, 4K $ + LP on Stargate for many months 1K+ STG staked and voted on proposals. Years of on-chain history including thousands of non-L0 tx's. YET THIS man includes me in this lol. @LayerZero-GH Hope you thoroughly study my wallet and do the correct thing.
