### ISSUE TITLE
[Sybil Report] Cluster of anishko.eth -  actively engaging wallets 

### ISSUE THREAD

**Issue by tharangabae** [LayerZero-Labs/sybil-report#7207]
# Reported Addresses

0x8a7c6b171dd5c2ac08162b7970fc2aa73035c963
0x6e05777c1c4bfe2190d51a3b47409df8a636b45a
0x1f8f40aeaec6850a20952edcafab8801f37bf631
0xb9382eebaaccf123e399fdca20b5f1b87922ed50
0x066ce3c1cd59cc37474387099e7f992bbb6aa6d0
0xc92fe7c1def867682d84ad29f7740acfe4a7a993

# Description

These 6 wallets farm the same airdrops and even shared the gas fees from same wallet + collect all the rewards to a same address. The same guy handle all wallets and those 6 wallets are actively engaging with the Layerzero past couple months.

# Detailed Methodology & Walkthrough

When using the debank and arkham platforms, We can easily identify these addresses have interconnected to share gas fees,  collect airdrops to a same address + deposit the funds to a same exchange.

![image](https://github.com/LayerZero-Labs/sybil-report/assets/134099296/87926eab-8c78-4e40-bd61-dcb826f58854)

here's the detailed visualization of these wallets interconnections. 
https://platform.arkhamintelligence.com/visualizer/entity/0x1F8F40AeAeC6850A20952EDCAfaB8801F37Bf631,0x8a7C6B171dd5C2aC08162B7970fC2aa73035C963,0x6E05777c1C4Bfe2190d51a3B47409dF8A636b45A,0x066ce3c1CD59cc37474387099E7f992BBB6Aa6d0,0xb9382eeBAaCCF123E399FdcA20B5F1b87922ED50,0xC92FE7C1DeF867682D84ad29f7740ACFe4A7a993?flow=self&positions=%7B%22merkly%22%3A%7B%22fx%22%3A192%2C%22fy%22%3A-6%7D%2C%220x8a7C6B171dd5C2aC08162B7970fC2aa73035C963%22%3A%7B%22fx%22%3A149%2C%22fy%22%3A-2%7D%2C%220xb9382eeBAaCCF123E399FdcA20B5F1b87922ED50%22%3A%7B%22fx%22%3A62%2C%22fy%22%3A66%7D%2C%220x1F8F40AeAeC6850A20952EDCAfaB8801F37Bf631%22%3A%7B%22fx%22%3A-16%2C%22fy%22%3A-65%7D%2C%220x066ce3c1CD59cc37474387099E7f992BBB6Aa6d0%22%3A%7B%22fx%22%3A74%2C%22fy%22%3A-67%7D%2C%220x6E05777c1C4Bfe2190d51a3B47409dF8A636b45A%22%3A%7B%22fx%22%3A-105%2C%22fy%22%3A-20%7D%2C%220xC92FE7C1DeF867682D84ad29f7740ACFe4A7a993%22%3A%7B%22fx%22%3A-86%2C%22fy%22%3A58%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

![image](https://github.com/LayerZero-Labs/sybil-report/assets/134099296/8f5403bd-de16-48ef-8060-61080cbed980)
above screenshot taken from debank to identify this sybil user activities. The wallet can find from below link

https://debank.com/profile/0x6e05777c1c4bfe2190d51a3b47409df8a636b45a/history?chain=eth

# Reward Address (If Eligible)

0x46db079a1e3d9F73080Cc31761B2dEA22f1dA2E9

**Comment by anishk5555** [comment]
@tharangabae please read the rules of reporting first before reporting anything. it should be a cluster of more than 20 wallets.

**Comment by tharangabae** [comment]
lol , 2 sybil wallets = Still sybil , Be greatful I only revealed 6. I can Dig more upto 20.Your call dude

LMEOW this is the funniest shit I heard in a while

**Comment by anishk5555** [comment]
@LayerZero-GH please reject this report as its not meeting the criteria more than 20 wallets.

**Comment by tharangabae** [comment]
Gonna cry you little sybil rat?

**Comment by anishk5555** [comment]
Hello @tharangabae  i have no issue with you. its your call to find out sybil wallets and report. its an opportunity layerzero is giving so you can use this valuable time to find out people who has more than 20 wallets. As per the rules of reporting more than 20 wallet cluster user is considered as a sybil and can be reported with analysis. Take care

**Comment by tharangabae** [comment]
I'm just a civilian fighting against shittiest sybil farmooors. If you think you are innocent , Let's see how @LayerZero-GH thinks. 6 wallets are good enough to report . Good luck to you Mr. anishko.eth
