### ISSUE TITLE
Suspicious Address [Sybil Report]

### ISSUE THREAD

**Issue by kopforlife** [LayerZero-Labs/sybil-report#7237]
# Reported Addresses
wrong list posted. 

# Description
Possible Sybil Address for LayerZero

# Detailed Methodology & Walkthrough
Filtering by transaction counts >150 and grouping them by clusters to check inter-wallet transfer for every 3 day period. Perform retracement analysis to see the route taken to generate volume and these matches a certain pattern.

# Reward Address (If Eligible)
0x223681c67C813EAa726772632c388fFF5a650d38

**Comment by berkay0625** [comment]
How logical is it to report a wallet that has been used for 1000+ days, has a balance of over $15K, and is used on more than 20 networks? I use it regularly every day.

**Comment by jay313027598** [comment]
杂种。瞎鸡吧举报。明天把你妈骨灰扬了

**Comment by berkay0625** [comment]
> 杂种。瞎鸡吧举报。明天把你妈骨灰扬了

this is the person complaining

https://x.com/kop_hello/status/1760635756517937634?s=46

**Comment by berkay0625** [comment]
![IMG_0795](https://github.com/LayerZero-Labs/sybil-report/assets/35797899/d46cb92f-95d8-4cdc-abeb-b77972179f14) The first thing I'll do when I get home is complain about you. I see you have multiple wallets linked together. It's a shame that you forget what you did while complaining about honest people.

**Comment by miche-britan** [comment]
this report is nonsense, the wheel is going to turn and you're going to find yourself eliminated with your wallets. don't play this game with fetching honorable people with no argument

**Comment by berkay0625** [comment]
> this report is nonsense, the wheel is going to turn and you're going to find yourself eliminated with your wallets. don't play this game with fetching honorable people with no argument

He has more than 4 wallets using Layerzero. I searched for a minute and found it. I'll know more when I get home
